name: animated_float_action_button
description: Allows you to create a collapsible list of float buttons.
version: 1.0.3-nullsafety.0
homepage: https://github.com/macielcr7/animated_float_action_button

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
